name: Build artifacts and attach to release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  header:
    uses: ./.github/workflows/header.yml

  staticlibs:
    uses: ./.github/workflows/staticlib.yml

  attach-artifacts:
    runs-on: ubuntu-latest
    needs:
      - header
      - staticlibs

    steps:
      - name: Download Static Library Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List Artifacts
        run: ls -R ./artifacts

      - name: Compress Static Library Files
        run: |
          for dir in ./artifacts/*; do
            if [ -d "$dir" ] && [ -f "$dir/liblinmem.a" ]; then
              base_name=$(basename "$dir")
              zip -j "./artifacts/${base_name}.zip" "$dir/liblinmem.a"
              rm -rf "$dir"
            fi
          done

      - name: Attach Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**
