name: Build staticlibs for liblinmem

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    strategy:
      matrix:
        include:
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-ios
          - os: macos-latest
            rust_target: aarch64-apple-ios-sim
          - os: macos-latest
            rust_target: x86_64-apple-ios
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - os: windows-latest
            rust_target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup default stable

      - name: Install Rust Target
        run: rustup target add ${{ matrix.rust_target }}

      - name: Build Static Library
        run: |
          cargo build --release --target ${{ matrix.rust_target }}
          mkdir -p liblinmem/${{ matrix.rust_target }}
          mv target/${{ matrix.rust_target }}/release/liblinmem.a liblinmem/${{ matrix.rust_target }}/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: liblinmem-${{ matrix.rust_target }}.a
          path: liblinmem/${{ matrix.rust_target }}